### ISSUE TITLE
null-safety support

### ISSUE THREAD

**Issue by tonnyavery** [shanus/flutter_suncalc#4]
Hi.
With the library provided mostly a set of utility methods it shouldn't a big effort to make it null-safety compatible so that dart doesn't complain during migration steps.
Thanks

**Comment by boymustafa** [comment]
> Hi.
> With the library provided mostly a set of utility methods it shouldn't a big effort to make it null-safety compatible so that dart doesn't complain during migration steps.
> Thanks

+1.  Is there any update on this?

**Comment by boymustafa** [comment]
@AAverin 
I found another library that is similar to this library but it supports null-safety. YOu can check it here https://pub.dev/packages/dart_suncalc

**Comment by tonnyavery** [comment]
Thanks, I'll check it out. I have also made a PR will null safety support

**Comment by shanus** [comment]
PR accepted and now supports null safety
